# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pickle

model = pickle.load(open("bmipredictor.sav","rb"))


class Ui_Form(object):

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(230, 90, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(60,-10,104,64))
        self.label.setText("Enter Height")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(60, 30, 104, 64))
        self.textEdit.setObjectName("textEdit")
        self.label_1 = QtWidgets.QLabel(Form)
        self.label_1.setGeometry(QtCore.QRect(60, 70, 104, 64))
        self.label_1.setText("Enter Weight")
        self.textEdit_2 = QtWidgets.QTextEdit(Form)
        self.textEdit_2.setGeometry(QtCore.QRect(60, 110, 104, 64))
        self.textEdit_2.setObjectName("textEdit_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "ShowBMI"))
        self.pushButton.clicked.connect(self.clickme)
        value = self.textEdit.toPlainText()

    def clickme(self):

        message = model.predict([[12,34]])
        msg = QtWidgets.QMessageBox()
        Height = self.textEdit.toPlainText()
        Weight = self.textEdit_2.toPlainText()

        BMI = model.predict([[int(Height), int(Weight)]])

        # setting message for Message Box
        msg.setText("Your BMI is "+ str(round(BMI[0][0],2)))


        # setting Message box window title
        msg.setWindowTitle("BMI")

        # declaring buttons on Message Box

        msg.exec_()
        sys.exit()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
